name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - '**.md'

# Cancel previous PR builds.
concurrency:
  # Cancel all workflow runs except latest within a concurrency group. This is achieved by defining a concurrency group for the PR.
  # Non-PR builds have singleton concurrency groups.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [
          "3.10",
          "3.11",
          "3.12",
          "3.13",
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          ./test-sep-dp.sh
